name: Cleaner Rivers
version: 0.3.1

pipeline:
  - src.plugins.disk_clay
  - src.plugins.disk_sand
  - src.plugins.disk_gravel

meta:
  base_version: "1.21.9"

data_pack:
  load: src/datapack
  description: {"text":"Cleaner Rivers\n1.21.9 - 26.1", "color":"gray"}
  min_format: 82
  max_format: 101

output: build
